server:
  port: 8222
eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: labeldetector
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/labeldetector/**
        - id: dataobject
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/dataobject/**